### ISSUE TITLE
Wrong composer dependency

### ISSUE THREAD

**Issue by simonschaufi** [punktDe/codeception-mailhog#2]
The correct way to include dependencies in order for other packages to make us of it is: `require` instead of `require-dev`. See https://github.com/punktDe/codeception-mailhog/blob/master/composer.json#L5

**Comment by kabarakh** [comment]
Usually test packages are within `require-dev` so they are not built for production context and thus not deployed on production. 
What you can do is add the packages we add in `require-dev` to the `require` block in your own project's `composer.json`, then you can control in which context they are installed

**Comment by simonschaufi** [comment]
Right but the moment you have a dependency across multiple repositories only the "require"d dependencies are fetched. In this case, if I define this package in my own root composer json in the "require-dev" section, any dependencies that THIS repository has don't take affect and `neos/utility-arrays` doesn't get installed. That's the problem.

**Comment by kabarakh** [comment]
Hi @simonschaufi,

during the update to codeception 4 we changed dev dependencies to dependencies. If you won't do the update, you can always add the dependency to your own composer root file.

Regards,
Christian Keuerleber

**Comment by simonschaufi** [comment]
@kabarakh thanks for the fix
